version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/trackwyse-backend-node
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start
      timeout: 300
      runas: ubuntu
